import { describe, it, expect } from 'vitest';
import {
  LEARNINGS_SECTIONS,
  TOKEN_BUDGET,
  GUILD_LEARNINGS_PATH,
  estimateTokens,
  isWithinBudget,
  renderEmptyLearnings,
  parseLearnings,
  renderLearnings,
  buildContextInjection,
} from '../learnings.js';

// --- Constants ---

describe('LEARNINGS_SECTIONS', () => {
  it('has exactly 5 sections', () => {
    expect(LEARNINGS_SECTIONS).toHaveLength(5);
  });

  it('contains the 5 spec-defined section names', () => {
    expect(LEARNINGS_SECTIONS).toContain('Project Patterns');
    expect(LEARNINGS_SECTIONS).toContain('Architecture Decisions');
    expect(LEARNINGS_SECTIONS).toContain('Past Issues & Resolutions');
    expect(LEARNINGS_SECTIONS).toContain('User Preferences');
    expect(LEARNINGS_SECTIONS).toContain('Agent Notes');
  });
});

describe('TOKEN_BUDGET', () => {
  it('equals 2000', () => {
    expect(TOKEN_BUDGET).toBe(2000);
  });
});

describe('GUILD_LEARNINGS_PATH', () => {
  it('points to .claude/guild/learnings.md', () => {
    expect(GUILD_LEARNINGS_PATH).toBe('.claude/guild/learnings.md');
  });
});

// --- estimateTokens ---

describe('estimateTokens', () => {
  it('returns 0 for empty string', () => {
    expect(estimateTokens('')).toBe(0);
  });

  it('returns 0 for null', () => {
    expect(estimateTokens(null)).toBe(0);
  });

  it('returns 0 for undefined', () => {
    expect(estimateTokens(undefined)).toBe(0);
  });

  it('returns 0 for whitespace-only', () => {
    expect(estimateTokens('   \n\t  ')).toBe(0);
  });

  it('returns positive number for a single word', () => {
    expect(estimateTokens('hello')).toBeGreaterThan(0);
  });

  it('returns a reasonable estimate for known text', () => {
    // 10 words × 1.35 = 13.5 → ceil → 14
    const text = 'one two three four five six seven eight nine ten';
    expect(estimateTokens(text)).toBe(14);
  });

  it('scales proportionally with text length', () => {
    const short = 'a b c d e';
    const long = 'a b c d e f g h i j k l m n o p q r s t';
    expect(estimateTokens(long)).toBeGreaterThan(estimateTokens(short));
  });
});

// --- isWithinBudget ---

describe('isWithinBudget', () => {
  it('returns true for short text', () => {
    expect(isWithinBudget('Hello world')).toBe(true);
  });

  it('returns false for very long text', () => {
    const longText = Array(2000).fill('word').join(' ');
    expect(isWithinBudget(longText)).toBe(false);
  });

  it('respects custom budget parameter', () => {
    const text = 'one two three four five'; // 5 words × 1.35 = 7 tokens
    expect(isWithinBudget(text, 10)).toBe(true);
    expect(isWithinBudget(text, 3)).toBe(false);
  });

  it('returns true for empty/null text', () => {
    expect(isWithinBudget('')).toBe(true);
    expect(isWithinBudget(null)).toBe(true);
  });
});

// --- renderEmptyLearnings ---

describe('renderEmptyLearnings', () => {
  it('contains the project name', () => {
    const output = renderEmptyLearnings('my-project');
    expect(output).toContain('# Guild Learnings — my-project');
  });

  it('contains all 5 section headings', () => {
    const output = renderEmptyLearnings();
    for (const section of LEARNINGS_SECTIONS) {
      expect(output).toContain(`## ${section}`);
    }
  });

  it('contains total executions: 0', () => {
    const output = renderEmptyLearnings();
    expect(output).toContain('> Total executions: 0');
  });

  it('contains token budget notice', () => {
    const output = renderEmptyLearnings();
    expect(output).toContain('Token budget');
  });

  it('contains placeholder text for each section', () => {
    const output = renderEmptyLearnings();
    const placeholders = output.match(/_No learnings yet\._/g);
    expect(placeholders).toHaveLength(5);
  });

  it('uses default project name when none provided', () => {
    const output = renderEmptyLearnings();
    expect(output).toContain('# Guild Learnings — Project');
  });
});

// --- parseLearnings ---

const SAMPLE_LEARNINGS = `# Guild Learnings — test-project

> Auto-generated by Guild. Last updated: 2026-02-25T10:00:00.000Z
> Total executions: 3
> Token budget: this file should stay under 2000 tokens

## Project Patterns

- Error handling uses AppException hierarchy with error codes (discovered: 2026-02-24)
- Naming: services use PascalCase (discovered: 2026-02-25)

## Architecture Decisions

- Auth uses JWT with refresh tokens (discovered: 2026-02-23)

## Past Issues & Resolutions

_No learnings yet._

## User Preferences

- Prefers early returns over nested if/else (discovered: 2026-02-24)

## Agent Notes

- code-reviewer: auth changes need extra scrutiny (discovered: 2026-02-25)
`;

describe('parseLearnings', () => {
  it('parses header fields', () => {
    const result = parseLearnings(SAMPLE_LEARNINGS);
    expect(result.header.project).toBe('test-project');
    expect(result.header.lastUpdated).toBe('2026-02-25T10:00:00.000Z');
    expect(result.header.totalExecutions).toBe(3);
  });

  it('parses entries per section', () => {
    const result = parseLearnings(SAMPLE_LEARNINGS);
    expect(result.sections['Project Patterns']).toHaveLength(2);
    expect(result.sections['Architecture Decisions']).toHaveLength(1);
    expect(result.sections['Past Issues & Resolutions']).toHaveLength(0);
    expect(result.sections['User Preferences']).toHaveLength(1);
    expect(result.sections['Agent Notes']).toHaveLength(1);
  });

  it('extracts discovered dates from entries', () => {
    const result = parseLearnings(SAMPLE_LEARNINGS);
    expect(result.sections['Project Patterns'][0].discovered).toBe('2026-02-24');
    expect(result.sections['Architecture Decisions'][0].discovered).toBe('2026-02-23');
  });

  it('returns empty structure for empty string', () => {
    const result = parseLearnings('');
    expect(result.header.project).toBe('');
    expect(result.header.totalExecutions).toBe(0);
    for (const section of LEARNINGS_SECTIONS) {
      expect(result.sections[section]).toEqual([]);
    }
  });

  it('returns empty structure for null', () => {
    const result = parseLearnings(null);
    for (const section of LEARNINGS_SECTIONS) {
      expect(result.sections[section]).toEqual([]);
    }
  });

  it('handles content with no entries in any section', () => {
    const empty = renderEmptyLearnings('empty-project');
    const result = parseLearnings(empty);
    expect(result.header.project).toBe('empty-project');
    for (const section of LEARNINGS_SECTIONS) {
      expect(result.sections[section]).toEqual([]);
    }
  });

  it('ignores unknown sections', () => {
    const content = '# Guild Learnings — test\n\n## Unknown Section\n\n- entry one\n';
    const result = parseLearnings(content);
    expect(result.sections['Unknown Section']).toBeUndefined();
  });
});

// --- renderLearnings ---

describe('renderLearnings', () => {
  it('renders a parsed structure back to markdown', () => {
    const parsed = parseLearnings(SAMPLE_LEARNINGS);
    const rendered = renderLearnings(parsed);
    expect(rendered).toContain('# Guild Learnings — test-project');
    expect(rendered).toContain('## Project Patterns');
    expect(rendered).toContain('- Error handling uses AppException');
    expect(rendered).toContain('- Auth uses JWT');
  });

  it('preserves section entry counts in round-trip', () => {
    const parsed = parseLearnings(SAMPLE_LEARNINGS);
    const rendered = renderLearnings(parsed);
    const reparsed = parseLearnings(rendered);

    for (const section of LEARNINGS_SECTIONS) {
      expect(reparsed.sections[section].length).toBe(parsed.sections[section].length);
    }
  });

  it('renders empty sections with placeholder', () => {
    const parsed = parseLearnings(SAMPLE_LEARNINGS);
    const rendered = renderLearnings(parsed);
    // Past Issues has no entries — should have placeholder
    expect(rendered).toContain('_No learnings yet._');
  });

  it('renders empty learnings correctly', () => {
    const emptyParsed = parseLearnings('');
    const rendered = renderLearnings(emptyParsed);
    for (const section of LEARNINGS_SECTIONS) {
      expect(rendered).toContain(`## ${section}`);
    }
    const placeholders = rendered.match(/_No learnings yet\._/g);
    expect(placeholders).toHaveLength(5);
  });
});

// --- buildContextInjection ---

describe('buildContextInjection', () => {
  it('returns empty string for null', () => {
    expect(buildContextInjection(null)).toBe('');
  });

  it('returns empty string for empty string', () => {
    expect(buildContextInjection('')).toBe('');
  });

  it('returns empty string for content with no entries', () => {
    const empty = renderEmptyLearnings();
    expect(buildContextInjection(empty)).toBe('');
  });

  it('returns empty string for whitespace-only content', () => {
    expect(buildContextInjection('   \n\t  ')).toBe('');
  });

  it('wraps content in guild-learnings tags', () => {
    const result = buildContextInjection(SAMPLE_LEARNINGS);
    expect(result).toContain('<guild-learnings>');
    expect(result).toContain('</guild-learnings>');
  });

  it('includes the instructional suffix', () => {
    const result = buildContextInjection(SAMPLE_LEARNINGS);
    expect(result).toContain('accumulated learnings from previous Guild executions');
    expect(result).toContain('Do not contradict established patterns');
  });

  it('includes the learnings content', () => {
    const result = buildContextInjection(SAMPLE_LEARNINGS);
    expect(result).toContain('Error handling uses AppException');
    expect(result).toContain('Auth uses JWT');
  });
});
