/**
 * generators.js — Generates the project state files (v1)
 */

import { writeFileSync } from 'fs';
import { wrapZone } from './zones.js';

/**
 * Generates PROJECT.md with the onboarding data.
 * V1: raw metadata only — CLAUDE.md holds the enriched context.
 */
export async function generateProjectMd(data) {
  const date = new Date().toISOString().split('T')[0];

  let content = `# PROJECT.md
> Generated by Guild v1 on ${date}

## Project
- **Name:** ${data.name}
- **Type:** ${data.type}
- **Stack:** ${data.stack}
- **Existing code:** ${data.hasExistingCode ? 'Yes' : 'No'}
`;

  if (data.github?.repoUrl) {
    content += `
## GitHub
- **Repository:** ${data.github.repoUrl}
`;
  }

  writeFileSync('PROJECT.md', content, 'utf8');
}

/**
 * Infers code conventions based on project type and stack.
 * Rules accumulate (not exclusive). Deduplicates lines.
 */
export function inferCodeConventions(type, stack) {
  const s = (stack || '').toLowerCase();
  const rules = [];

  // Stack-specific rules
  if (s.includes('next') || s.includes('react')) {
    rules.push('- Components in PascalCase', '- CSS Modules or Tailwind utility classes');
  }
  if (s.includes('express') || (s.includes('node') && type === 'api')) {
    rules.push('- Controllers/routes pattern', '- Async/await error handling');
  }
  if (s.includes('typescript') || /\bts\b/.test(s)) {
    rules.push('- Strict TypeScript', '- Interfaces over types where possible');
  }

  // Type-specific fallbacks (only if no stack rules matched)
  if (rules.length === 0) {
    if (type === 'cli') {
      rules.push('- Commander.js command pattern', '- ESModules throughout');
    } else if (type === 'api') {
      rules.push('- REST or GraphQL endpoint conventions', '- Input validation on all endpoints');
    } else {
      rules.push('- Consistent naming conventions', '- ESModules throughout');
    }
  }

  // Deduplicate
  return [...new Set(rules)].join('\n');
}

/**
 * Infers likely environment variables based on project type and stack.
 * Rules accumulate. Deduplicates lines.
 */
export function inferEnvVars(type, stack) {
  const s = (stack || '').toLowerCase();
  const vars = [];

  // Stack-specific
  if (s.includes('supabase')) vars.push('- `SUPABASE_URL`', '- `SUPABASE_ANON_KEY`');
  if (s.includes('firebase')) vars.push('- `FIREBASE_API_KEY`', '- `FIREBASE_PROJECT_ID`');
  if (s.includes('postgres')) vars.push('- `DATABASE_URL`');
  if (s.includes('redis')) vars.push('- `REDIS_URL`');
  if (s.includes('stripe')) vars.push('- `STRIPE_SECRET_KEY`', '- `STRIPE_WEBHOOK_SECRET`');
  if (s.includes('vercel')) vars.push('- `VERCEL_URL`');
  if (/\baws\b/.test(s)) vars.push('- `AWS_ACCESS_KEY_ID`', '- `AWS_SECRET_ACCESS_KEY`', '- `AWS_REGION`');

  // Type-specific fallbacks
  if (vars.length === 0) {
    if (type === 'webapp') vars.push('- `NODE_ENV`', '- `API_URL`');
    else if (type === 'api') vars.push('- `NODE_ENV`', '- `PORT`', '- `DATABASE_URL`');
    else vars.push('- `NODE_ENV`');
  }

  return [...new Set(vars)].join('\n');
}

/**
 * Generates CLAUDE.md — central document with placeholders for guild-specialize.
 */
export async function generateClaudeMd(data) {
  const content = `# ${data.name}

## Framework
This project uses Guild. Read SESSION.md at the start of each session.

## Stack
${data.stack}

## Project structure
${wrapZone('structure', '[PENDING: guild-specialize]\n\ndocs/\n  specs/                              # Design documents (SDD specs)')}

## Code conventions
${wrapZone('conventions', inferCodeConventions(data.type, data.stack))}

## Architecture patterns
${wrapZone('architecture', '[PENDING: guild-specialize]')}

## Environment variables
${wrapZone('env-vars', inferEnvVars(data.type, data.stack))}

## Global rules
- Do not implement without an approved plan
- Update SESSION.md at the end of each session
- ESModules throughout the codebase
- Always use path.join() to build paths

## Subagent rules
- Guild agent roles (advisor, developer, tech-lead, etc.) are NOT Claude Code subagent_types
- Always use \`subagent_type: "general-purpose"\` when spawning agents via Task tool
- CLAUDE.md and SESSION.md changes must be committed separately from feature code
- No \`git stash\` in automated pipelines — use \`wip:\` commits instead
- Parallel agents must use git worktrees for isolation

## Available skills
- /guild-specialize  — enrich CLAUDE.md by exploring the actual project
- /build-feature     — full development pipeline
- /new-feature       — create branch and scaffold for a feature
- /create-pr         — create a structured pull request from current branch
- /council           — debate decisions with multiple agents
- /review            — code review on the current diff
- /qa-cycle          — QA + bugfix cycle
- /status            — view project status
- /dev-flow          — view current pipeline phase
- /session-start     — load context and resume work
- /session-end       — save state to SESSION.md
`;

  writeFileSync('CLAUDE.md', content, 'utf8');
}

/**
 * Generates initial SESSION.md.
 */
export async function generateSessionMd() {
  const date = new Date().toISOString().split('T')[0];

  const content = `# SESSION.md

## Active session
- **Date:** ${date}
- **Current task:** —
- **Active agent:** —
- **Status:** Project just initialized with Guild v1

## Relevant context
- Onboarding completed. See PROJECT.md for project data.
- CLAUDE.md has placeholders — run /guild-specialize to enrich.

## Next steps
1. Run /guild-specialize to analyze your codebase
2. Spec your first feature with /council
3. Build it with /build-feature
`;

  writeFileSync('SESSION.md', content, 'utf8');
}
