/**
 * generators.js — Generates the project state files (v1)
 */

import { writeFileSync } from 'fs';

/**
 * Generates PROJECT.md with the onboarding data.
 * V1: raw metadata only — CLAUDE.md holds the enriched context.
 */
export async function generateProjectMd(data) {
  const date = new Date().toISOString().split('T')[0];

  let content = `# PROJECT.md
> Generated by Guild v1 on ${date}

## Project
- **Name:** ${data.name}
- **Type:** ${data.type}
- **Stack:** ${data.stack}
- **Existing code:** ${data.hasExistingCode ? 'Yes' : 'No'}
`;

  if (data.github?.repoUrl) {
    content += `
## GitHub
- **Repository:** ${data.github.repoUrl}
`;
  }

  writeFileSync('PROJECT.md', content, 'utf8');
}

/**
 * Generates CLAUDE.md — central document with placeholders for guild-specialize.
 */
export async function generateClaudeMd(data) {
  const content = `# ${data.name}

## Framework
This project uses Guild. Read SESSION.md at the start of each session.

## Stack
${data.stack}

## Project structure
[PENDING: guild-specialize]

## Code conventions
[PENDING: guild-specialize]

## Architecture patterns
[PENDING: guild-specialize]

## Environment variables
[PENDING: guild-specialize]

## Global rules
- Do not implement without an approved plan
- Update SESSION.md at the end of each session
- ESModules throughout the codebase
- Always use path.join() to build paths

## Subagent rules
- Guild agent roles (advisor, developer, tech-lead, etc.) are NOT Claude Code subagent_types
- Always use \`subagent_type: "general-purpose"\` when spawning agents via Task tool
- CLAUDE.md and SESSION.md changes must be committed separately from feature code
- No \`git stash\` in automated pipelines — use \`wip:\` commits instead
- Parallel agents must use git worktrees for isolation

## Available skills
- /guild-specialize  — enrich CLAUDE.md by exploring the actual project
- /build-feature     — full development pipeline
- /new-feature       — create branch and scaffold for a feature
- /council           — debate decisions with multiple agents
- /review            — code review on the current diff
- /qa-cycle          — QA + bugfix cycle
- /status            — view project status
- /dev-flow          — view current pipeline phase
- /session-start     — load context and resume work
- /session-end       — save state to SESSION.md
`;

  writeFileSync('CLAUDE.md', content, 'utf8');
}

/**
 * Generates initial SESSION.md.
 */
export async function generateSessionMd() {
  const date = new Date().toISOString().split('T')[0];

  const content = `# SESSION.md

## Active session
- **Date:** ${date}
- **Current task:** —
- **Active agent:** —
- **Status:** Project just initialized with Guild v1

## Relevant context
- Onboarding completed. See PROJECT.md for project data.
- CLAUDE.md has placeholders — run /guild-specialize to enrich.

## Next steps
1. Open Claude Code and run /guild-specialize
2. Define the first feature with /build-feature
`;

  writeFileSync('SESSION.md', content, 'utf8');
}
