/**
 * learnings.js — Pure functions for compound learning.
 *
 * Constants, parsing, rendering, token estimation, and context injection.
 * Zero I/O, zero external dependencies — leaf module.
 */

/** Fixed section names for the learnings file (spec section 3.3). */
export const LEARNINGS_SECTIONS = [
  'Project Patterns',
  'Architecture Decisions',
  'Past Issues & Resolutions',
  'User Preferences',
  'Agent Notes',
];

/** Maximum token budget for the learnings file. */
export const TOKEN_BUDGET = 2000;

/** Default path to the learnings file, relative to project root. */
export const GUILD_LEARNINGS_PATH = '.claude/guild/learnings.md';

/**
 * Estimates token count from text using a word-count heuristic.
 * Approximation: tokens ≈ ceil(words × 1.35).
 * @param {string | null | undefined} text
 * @returns {number}
 */
export function estimateTokens(text) {
  if (!text || !text.trim()) return 0;
  const words = text.trim().split(/\s+/).length;
  return Math.ceil(words * 1.35);
}

/**
 * Returns true if the estimated token count is within the budget.
 * @param {string | null | undefined} text
 * @param {number} [budget=TOKEN_BUDGET]
 * @returns {boolean}
 */
export function isWithinBudget(text, budget = TOKEN_BUDGET) {
  return estimateTokens(text) <= budget;
}

/**
 * Renders the initial/empty learnings file content.
 * @param {string} [projectName='Project']
 * @returns {string}
 */
export function renderEmptyLearnings(projectName = 'Project') {
  const lines = [];
  lines.push(`# Guild Learnings — ${projectName}`);
  lines.push('');
  lines.push(`> Auto-generated by Guild. Last updated: ${new Date().toISOString()}`);
  lines.push('> Total executions: 0');
  lines.push('> Token budget: this file should stay under 2000 tokens');
  lines.push('');

  for (const section of LEARNINGS_SECTIONS) {
    lines.push(`## ${section}`);
    lines.push('');
    lines.push('_No learnings yet._');
    lines.push('');
  }

  return lines.join('\n');
}

const PLACEHOLDER_RE = /^_No learnings yet\._$/;
const ENTRY_RE = /^- (.+)$/;
const DISCOVERED_RE = /\(discovered: ([^)]+)\)/;

/**
 * Parses a learnings.md file into a structured object.
 * @param {string | null | undefined} content
 * @returns {{ header: { project: string, lastUpdated: string, totalExecutions: number }, sections: Record<string, Array<{ text: string, discovered: string }>> }}
 */
export function parseLearnings(content) {
  const empty = {
    header: { project: '', lastUpdated: '', totalExecutions: 0 },
    sections: {},
  };
  for (const s of LEARNINGS_SECTIONS) empty.sections[s] = [];

  if (!content || !content.trim()) return empty;

  const lines = content.split('\n');
  const result = { header: { project: '', lastUpdated: '', totalExecutions: 0 }, sections: {} };
  for (const s of LEARNINGS_SECTIONS) result.sections[s] = [];

  let currentSection = null;

  for (const line of lines) {
    // Parse H1 header
    const h1Match = line.match(/^# Guild Learnings — (.+)$/);
    if (h1Match) {
      result.header.project = h1Match[1].trim();
      continue;
    }

    // Parse header metadata
    const updatedMatch = line.match(/^> Auto-generated by Guild\. Last updated: (.+)$/);
    if (updatedMatch) {
      result.header.lastUpdated = updatedMatch[1].trim();
      continue;
    }
    const execMatch = line.match(/^> Total executions: (\d+)$/);
    if (execMatch) {
      result.header.totalExecutions = parseInt(execMatch[1], 10);
      continue;
    }

    // Parse section headers
    const h2Match = line.match(/^## (.+)$/);
    if (h2Match) {
      const sectionName = h2Match[1].trim();
      if (LEARNINGS_SECTIONS.includes(sectionName)) {
        currentSection = sectionName;
      } else {
        currentSection = null;
      }
      continue;
    }

    // Skip placeholders and blank lines
    if (!currentSection) continue;
    if (PLACEHOLDER_RE.test(line.trim())) continue;
    if (!line.trim()) continue;

    // Parse entries (lines starting with "- ")
    const entryMatch = line.match(ENTRY_RE);
    if (entryMatch) {
      const text = entryMatch[1].trim();
      const discoveredMatch = text.match(DISCOVERED_RE);
      result.sections[currentSection].push({
        text,
        discovered: discoveredMatch ? discoveredMatch[1] : '',
      });
    }
  }

  return result;
}

/**
 * Renders a parsed learnings structure back to markdown.
 * @param {{ header: { project: string, lastUpdated: string, totalExecutions: number }, sections: Record<string, Array<{ text: string, discovered: string }>> }} parsed
 * @returns {string}
 */
export function renderLearnings(parsed) {
  const lines = [];
  const project = parsed.header.project || 'Project';
  const lastUpdated = parsed.header.lastUpdated || new Date().toISOString();
  const totalExecutions = parsed.header.totalExecutions || 0;

  lines.push(`# Guild Learnings — ${project}`);
  lines.push('');
  lines.push(`> Auto-generated by Guild. Last updated: ${lastUpdated}`);
  lines.push(`> Total executions: ${totalExecutions}`);
  lines.push('> Token budget: this file should stay under 2000 tokens');
  lines.push('');

  for (const section of LEARNINGS_SECTIONS) {
    lines.push(`## ${section}`);
    lines.push('');
    const entries = parsed.sections[section] || [];
    if (entries.length === 0) {
      lines.push('_No learnings yet._');
    } else {
      for (const entry of entries) {
        lines.push(`- ${entry.text}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Builds a context injection string from raw learnings content.
 * Wraps in <guild-learnings> tags per spec section 4.2.
 * Returns empty string for null/empty input.
 * @param {string | null | undefined} content
 * @returns {string}
 */
export function buildContextInjection(content) {
  if (!content || !content.trim()) return '';

  const parsed = parseLearnings(content);
  const hasEntries = LEARNINGS_SECTIONS.some(s => (parsed.sections[s] || []).length > 0);
  if (!hasEntries) return '';

  const lines = [];
  lines.push('<guild-learnings>');
  lines.push(content.trim());
  lines.push('</guild-learnings>');
  lines.push('');
  lines.push('These are accumulated learnings from previous Guild executions on this project.');
  lines.push('Use them to inform your work. Do not contradict established patterns unless');
  lines.push('explicitly asked to change them.');

  return lines.join('\n');
}
